Add Docs (based on yard)
ManageIQ/virtfs pull request #18
Opened 2017-02-02 21:16 UTC by movitto

2017-02-02 23:41 UTC, movitto commented
@roliveri please review, just rdoc / yardoc additions, no functional changes. Would like to merge b4 it gets stale

2017-02-03 06:07 UTC, roliveri commented
@movitto Sorry, I should have merged this before my other PR. You'll have to rebase, but it doesn't look like the conflicts are too bad.

2017-02-03 23:26 UTC, roliveri requested changes

2017-02-03 23:26 UTC, roliveri commented on lib/virtfs/context.rb
> +  # FS-specific settings under which FS calls occur.
Actually the context maintains FS-specific _state_. That _state_ includes: what filesystems are mounted and where, the current working directory, and the current root.

2017-02-03 23:26 UTC, roliveri commented on lib/virtfs/context.rb
> +  # dispatching target FS calls. This class implements the
There is not an independent context per mounted FS instance. There is a context per thread group of the process - so normally, there will only be one context per process.

Due to the nature of constants in ruby, VirtFS _activation_ must be a process-while operation. When a given application requires a process to have multiple _views_ of the current FS state, multiple contexts can be used. By dividing the process into multiple thread-groups, each thread-group can have it's own view of the current FS state. For example, one group might only see the native filesystem, while others can see additional filesystems, or totally different filesystems. Basing contexts on thread-groups, as opposed to individual threads, permits multi-threaded filesystem access when necessary.

2017-02-03 23:26 UTC, roliveri commented on lib/virtfs/context.rb
> +    # point through VirtFS will be mapped through the specified fs instance
Should be:
...through VirtFS, **under this context**, will be mapped...

2017-02-03 23:26 UTC, roliveri commented on lib/virtfs/context.rb
>      def path_lookup(path, raise_full_path = false, include_last = true)
The methods defined from here to the end of file are not part of the public VirtFS interface (they are for internal use). I'm not sure if they should be included in the documentation - or minimally, it should be made clear they are for internal use only.

2017-02-03 23:26 UTC, roliveri commented on lib/virtfs/find_class_methods.rb
> +    # @param path [String] path to lookup
**path** is the starting directory of the _find_.

2017-02-03 23:26 UTC, roliveri commented on lib/virtfs/find_class_methods.rb
>      def dir_and_glob(glob_pattern)
Here too, the following methods are for internal use.

2017-02-06 23:23 UTC, movitto commented
@roliveri fixed the semantic issues and marked the noted methods as @api private meaning they can be hidden with the '--hide-api private' yardoc cli option

2017-02-06 23:23 UTC, movitto commented
Not sure how this  PR was auto-closed and y I can't reopen...

2017-02-07 18:20 UTC, roliveri requested changes
@movitto please don't squash commits, it makes it harder to review incremental changes.

Also, when documenting methods that are just re-implementations of their standard Ruby counterparts, I wonder if we should just refer to the standard Ruby documentation.

2017-02-07 18:20 UTC, roliveri commented on lib/virtfs/context_switch_class_methods.rb
> +    #
I think this should be `@api private` as well.

2017-02-07 18:20 UTC, roliveri commented on lib/virtfs/context_switch_class_methods.rb
> +  # @see Context#path_lookup
I think this should be `@api private` as well.

2017-02-07 18:20 UTC, roliveri commented on lib/virtfs/find_class_methods.rb
> +    # @param path [String] starting director of the find
typo: director should be directory

2017-02-08 16:24 UTC, movitto commented on lib/virtfs/find_class_methods.rb
> +    # @param path [String] starting director of the find
@updated

2017-02-08 16:24 UTC, movitto commented on lib/virtfs/context_switch_class_methods.rb
> +  # @see Context#path_lookup
@updated

2017-02-08 16:24 UTC, movitto commented on lib/virtfs/context_switch_class_methods.rb
> +    #
@roliveri updated

2017-02-08 16:25 UTC, movitto commented
@roliveri yes that makes sense (I believe we can link directly to it for the yardocs). Perhaps this can be done in a subsequent PR though so as not to hold things up.

2017-02-08 18:17 UTC, roliveri commented
and yet, you still squashed the commits.

2017-02-08 18:17 UTC, merged

2017-02-08 22:59 UTC, movitto commented
@roliveri srry thought you were referring to the other PR (virtfs-ext3), forgot if this one had separate commits to begin with (switching back and force between several virtfs projects, tricky to keep track!)